#pragma once

#define _SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING
#define APEX
//#define TTF2

#include <string>
#include <Windows.h>
#undef min
#undef max
#include <fmt/format.h>
#include <locale>
#include <codecvt>
#include <fstream>
#include <vector>
#include <spdlog/spdlog.h>
#include <filesystem>
#include <d3d11.h>
#include <DirectXTex.h>
#include <Windows.Foundation.h>
#include <wrl/wrappers/corewrappers.h>
#include <wrl/client.h>
#include <nlohmann/json.hpp>
#include "d3d.h"
#include "CLI11.hpp"
#include "rtech.h"
#include "KnownAssetCache.h"
#include "IAsset.h"
#include "common/common_types.h"
#include "ttf2/ttf2_types.h"
#include "apex/apex_types.h"
#include "Util.h"
#include "IDecompressedFileReader.h"
#include "CompressedFileReader.h"
#include "AssetFactory.h"
#include "ChainedReader.h"
#include "PreprocessedFileReader.h"
#include "rpak.h"